"""
This type stub file was generated by pyright.
"""

from pxr.UsdUtils.constantsGroup import ConstantsGroup

class NodeTypes(ConstantsGroup):
    UsdPreviewSurface = ...
    UsdUVTexture = ...
    UsdTransform2d = ...
    UsdPrimvarReader = ...


class ShaderProps(ConstantsGroup):
    Bias = ...
    Scale = ...
    SourceColorSpace = ...
    Normal = ...
    File = ...


class BaseRuleChecker:
    """This is Base class for all the rule-checkers."""
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def GetFailedChecks(self): # -> list[Any]:
        ...
    
    def GetErrors(self): # -> list[Any]:
        ...
    
    def GetWarnings(self): # -> list[Any]:
        ...
    
    def CheckStage(self, usdStage): # -> None:
        """ Check the given usdStage. """
        ...
    
    def CheckDiagnostics(self, diagnostics): # -> None:
        """ Check the diagnostic messages that were generated when opening the 
            USD stage. The diagnostic messages are collected using a 
            UsdUtilsCoalescingDiagnosticDelegate.
        """
        ...
    
    def CheckUnresolvedPaths(self, unresolvedPaths): # -> None:
        """ Check or process any unresolved asset paths that were found when 
            analysing the dependencies.
        """
        ...
    
    def CheckDependencies(self, usdStage, layerDeps, assetDeps): # -> None:
        """ Check usdStage's layer and asset dependencies that were gathered 
            using UsdUtils.ComputeAllDependencies().
        """
        ...
    
    def CheckLayer(self, layer): # -> None:
        """ Check the given SdfLayer. """
        ...
    
    def CheckZipFile(self, zipFile, packagePath): # -> None:
        """ Check the zipFile object created by opening the package at path 
            packagePath.
        """
        ...
    
    def CheckPrim(self, prim): # -> None:
        """ Check the given prim, which may only exist is a specific combination
            of variant selections on the UsdStage.
        """
        ...
    
    def ResetCaches(self): # -> None:
        """ Reset any caches the rule owns.  Called whenever stage authoring
        occurs, such as when we iterate through VariantSet combinations.
        """
        ...
    


class ByteAlignmentChecker(BaseRuleChecker):
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckZipFile(self, zipFile, packagePath): # -> None:
        ...
    


class CompressionChecker(BaseRuleChecker):
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckZipFile(self, zipFile, packagePath): # -> None:
        ...
    


class MissingReferenceChecker(BaseRuleChecker):
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckDiagnostics(self, diagnostics): # -> None:
        ...
    
    def CheckUnresolvedPaths(self, unresolvedPaths): # -> None:
        ...
    


class StageMetadataChecker(BaseRuleChecker):
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckStage(self, usdStage): # -> None:
        ...
    


class TextureChecker(BaseRuleChecker):
    _basicUSDZImageFormats = ...
    _unsupportedImageFormats = ...
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckStage(self, usdStage): # -> None:
        ...
    
    def CheckPrim(self, prim): # -> None:
        ...
    


class PrimEncapsulationChecker(BaseRuleChecker):
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckPrim(self, prim): # -> None:
        ...
    
    def ResetCaches(self): # -> None:
        ...
    


class NormalMapTextureChecker(BaseRuleChecker):
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckPrim(self, prim):
        ...
    


class MaterialBindingAPIAppliedChecker(BaseRuleChecker):
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckPrim(self, prim): # -> None:
        ...
    


class SkelBindingAPIAppliedChecker(BaseRuleChecker):
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckPrim(self, prim): # -> None:
        ...
    


class ShaderPropertyTypeConformanceChecker(BaseRuleChecker):
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckPrim(self, prim): # -> None:
        ...
    


class ARKitPackageEncapsulationChecker(BaseRuleChecker):
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckDependencies(self, usdStage, layerDeps, assetDeps): # -> None:
        ...
    


class ARKitLayerChecker(BaseRuleChecker):
    _allowedLayerFormatIds = ...
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckLayer(self, layer): # -> None:
        ...
    


class ARKitPrimTypeChecker(BaseRuleChecker):
    _allowedPrimTypeNames = ...
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckPrim(self, prim): # -> None:
        ...
    


class ARKitShaderChecker(BaseRuleChecker):
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckPrim(self, prim): # -> None:
        ...
    


class ARKitMaterialBindingChecker(BaseRuleChecker):
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckPrim(self, prim): # -> None:
        ...
    


class ARKitFileExtensionChecker(BaseRuleChecker):
    _allowedFileExtensions = ...
    @staticmethod
    def GetDescription(): # -> LiteralString:
        ...
    
    def __init__(self, verbose, consumerLevelChecks, assetLevelChecks) -> None:
        ...
    
    def CheckZipFile(self, zipFile, packagePath): # -> None:
        ...
    


class ComplianceChecker:
    """ A utility class for checking compliance of a given USD asset or a USDZ 
    package.

    Since usdz files are zip files, someone could use generic zip tools to 
    create an archive and just change the extension, producing a .usdz file that 
    does not honor the additional constraints that usdz files require.  Even if 
    someone does use our official archive creation tools, though, we 
    intentionally allow creation of usdz files that can be very "permissive" in 
    their contents for internal studio uses, where portability outside the 
    studio is not a concern.  For content meant to be delivered over the web 
    (eg. ARKit assets), however, we must be much more restrictive.

    This class provides two levels of compliance checking: 
    * "structural" validation that is represented by a set of base rules. 
    * "ARKit" compatibility validation, which includes many more restrictions.
    
    Calling ComplianceChecker.DumpAllRules() will print an enumeration of the 
    various rules in the two categories of compliance checking.
    """
    @staticmethod
    def GetBaseRules(): # -> list[Any]:
        ...
    
    @staticmethod
    def GetARKitRules(skipARKitRootLayerCheck=...): # -> list[Any]:
        ...
    
    @staticmethod
    def GetRules(arkit=..., skipARKitRootLayerCheck=...): # -> list[Any]:
        ...
    
    @staticmethod
    def DumpAllRules(): # -> None:
        ...
    
    def __init__(self, arkit=..., skipARKitRootLayerCheck=..., rootPackageOnly=..., skipVariants=..., verbose=..., assetLevelChecks=...) -> None:
        ...
    
    def GetErrors(self): # -> list[Any]:
        ...
    
    def GetWarnings(self): # -> list[Any]:
        ...
    
    def DumpRules(self): # -> None:
        ...
    
    def GetFailedChecks(self): # -> list[Any]:
        ...
    
    def CheckCompliance(self, inputFile): # -> None:
        ...
    


