"""
This type stub file was generated by pyright.
"""

"""A module for creating groups of constants. This is similar to the enum
module, but enum is not available in Python 2's standard library.
"""
class _MetaConstantsGroup(type):
    """A meta-class which handles the creation and behavior of ConstantsGroups.
    """
    def __new__(metacls, cls, bases, classdict): # -> Self:
        """Discover constants and create a new ConstantsGroup class."""
        ...
    
    def __setattr__(cls, name, value):
        """Prevent modification of properties after a group is created."""
        ...
    
    def __delattr__(cls, name):
        """Prevent deletion of properties after a group is created."""
        ...
    
    def __len__(self): # -> int:
        """Get the number of constants in the group."""
        ...
    
    def __contains__(self, value): # -> bool:
        """Check if a constant exists in the group."""
        ...
    
    def __iter__(self):
        """Iterate over each constant in the group."""
        ...
    


class ConstantsGroup(metaclass=_MetaConstantsGroup):
    """The base constant group class, intended to be inherited by actual groups
    of constants.
    """
    def __new__(cls, *args, **kwargs):
        ...
    


