"""
This type stub file was generated by pyright.
"""

def ExtractUsdzPackage(usdzFile, extractDir, recurse, verbose, force): # -> bool:
    """
    Given a usdz package usdzFile, extracts the contents of the archive under
    the extractDir directory. Since usdz packages can contain other usdz
    packages, recurse flag can be used to extract the nested structure
    appropriately.
    """
    ...

class UsdzAssetIterator:
    """
    Class that provides an iterator for usdz assets. Within context, it
    extracts the contents of the usdz package, provides generators for all usd
    files and all assets and on exit packs the extracted files back recursively 
    into a usdz package.
    Note that root layer of the usdz package might not be compliant which can
    cause UsdzAssetIterator to raise an exception while repacking on exit.
    """
    def __init__(self, usdzFile, verbose, parentDir=...) -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, excType, excVal, excTB): # -> None:
        ...
    
    def UsdAssets(self): # -> Generator[Any | None, Any, None]:
        """
        Generator for UsdAssets respecting nested usdz assets.
        """
        ...
    
    def AllAssets(self): # -> Generator[Any | None, Any, None]:
        """
        Generator for all assets packed in the usdz package, respecting nested
        usdz assets.
        """
        ...
    


