"""Minimal local stubs for pxr.UsdGeom while learning USD."""

from pxr import Gf, Sdf, Usd


class _SchemaBase:
    def GetPath(self) -> Sdf.Path: ...
    def GetPrim(self) -> Usd.Prim: ...


class Scope(_SchemaBase):
    @staticmethod
    def Define(stage: Usd.Stage, path: Sdf.Path | str) -> "Scope": ...


class Xform(_SchemaBase):
    @staticmethod
    def Define(stage: Usd.Stage, path: Sdf.Path | str) -> "Xform": ...


class Cube(_SchemaBase):
    @staticmethod
    def Define(stage: Usd.Stage, path: Sdf.Path | str) -> "Cube": ...

    def GetDisplayColorAttr(self) -> Usd.Attribute: ...
    def GetExtentAttr(self) -> Usd.Attribute: ...
    def GetSizeAttr(self) -> Usd.Attribute: ...


class Sphere(_SchemaBase):
    @staticmethod
    def Define(stage: Usd.Stage, path: Sdf.Path | str) -> "Sphere": ...

    def CreateRadiusAttr(self, defaultValue: object = ...) -> Usd.Attribute: ...


class XformCommonAPI:
    def __init__(self, schema: _SchemaBase | Usd.Prim) -> None: ...
    def SetTranslate(self, translation: Gf.Vec3d) -> bool: ...
