"""
This type stub file was generated by pyright.
"""

from pxr import Tf

"""Vt Value Types library

This package defines classes for creating objects that behave like value
types.  It contains facilities for creating simple copy-on-write
implicitly shared types.
"""
