"""
This type stub file was generated by pyright.
"""

import contextlib
from pxr import Tf

"""
Trace -- Utilities for counting and recording events.
"""
@contextlib.contextmanager
def TraceScope(label): # -> Generator[None, Any, None]:
    """A context manager that calls BeginEvent on the global collector on enter 
    and EndEvent on exit."""
    ...

def TraceFunction(obj): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    """A decorator that enables tracing the function that it decorates.
    If you decorate with 'TraceFunction' the function will be traced in the
    global collector."""
    ...

def TraceMethod(obj): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    """A convenience.  Same as TraceFunction but changes the recorded
    label to use the term 'method' rather than 'function'."""
    ...

