"""
This type stub file was generated by pyright.
"""

import platform
import sys
import contextlib

"""
Tf -- Tools Foundation
"""
if sys.version_info >= (3, 8) and platform.system() == "Windows":
    @contextlib.contextmanager
    def WindowsImportWrapper(): # -> Generator[None, Any, None]:
        ...
    
else:
    class WindowsImportWrapper:
        def __enter__(self): # -> None:
            ...
        
        def __exit__(self, exc_type, ex_val, exc_tb): # -> None:
            ...
        
    
    
def PreparePythonModule(moduleName=...): # -> None:
    """Prepare an extension module at import time.  This will import the
    Python module associated with the caller's module (e.g. '_tf' for 'pxr.Tf')
    or the module with the specified moduleName and copy its contents into
    the caller's local namespace.

    Generally, this should only be called by the __init__.py script for a module
    upon loading a boost python module (generally '_libName.so')."""
    ...

def PrepareModule(module, result): # -> None:
    """PrepareModule(module, result) -- Prepare an extension module at import
    time.  Generally, this should only be called by the __init__.py script for a
    module upon loading a boost python module (generally '_libName.so')."""
    ...

def GetCodeLocation(framesUp): # -> tuple[Any, str, str, int | Any]:
    """Returns a tuple (moduleName, functionName, fileName, lineNo).

    To trace the current location of python execution, use GetCodeLocation().
    By default, the information is returned at the current stack-frame; thus

        info = GetCodeLocation()

    will return information about the line that GetCodeLocation() was called 
    from. One can write:

        def genericDebugFacility():
            info = GetCodeLocation(1)
            # print out data


        def someCode():
            ...
            if bad:
                genericDebugFacility()

    and genericDebugFacility() will get information associated with its caller, 
    i.e. the function someCode()."""
    ...

class ErrorException(RuntimeError):
    def __init__(self, *args) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


def Warn(msg, template=...): # -> None:
    """Issue a warning via the TfDiagnostic system.

    At this time, template is ignored.
    """
    ...

def Status(msg, verbose=...): # -> None:
    """Issues a status update to the Tf diagnostic system.

    If verbose is True (the default) then information about where in the code
    the status update was issued from is included.
    """
    ...

def RaiseCodingError(msg): # -> None:
    """Raise a coding error to the Tf Diagnostic system."""
    ...

def RaiseRuntimeError(msg): # -> None:
    """Raise a runtime error to the Tf Diagnostic system."""
    ...

def Fatal(msg): # -> None:
    """Raise a fatal error to the Tf Diagnostic system."""
    ...

class NamedTemporaryFile:
    """A named temporary file which keeps the internal file handle closed. 
       A class which constructs a temporary file(that isn't open) on __enter__,
       provides its name as an attribute, and deletes it on __exit__. 
       
       Note: The constructor args for this object match those of 
       python's tempfile.mkstemp() function, and will have the same effect on
       the underlying file created."""
    def __init__(self, suffix=..., prefix=..., dir=..., text=...) -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    
    @property
    def name(self): # -> str:
        """The path for the temporary file created."""
        ...
    


class ScopeDescription(_ScopeDescription, contextlib.ContextDecorator):
    """This class lets us expose TfScopeDescription to python for use as a
    "context manager" object, for use with the 'with'-statement. For example:

        with Tf.ScopeDescription("Solving the halting problem"):
            # Code that solves the halting problem.

    It can also be used as a decorator for an entire function or method, for
    convenience:

        @Tf.ScopeDescription("Solving the halting problem");
        def SolveHaltingProblem():
            # Code that solves the halting problem.

    Note that the description passed to the decorator is an expression that is
    evaluated only once at declaration time. If a dynamic description is
    needed, use the with-statement pattern instead.
    """
    ...


class CatchAndRepostErrors(contextlib.ContextDecorator):
    """This context manager & decorator can be used to catch Tf.ErrorException
    and repost its held errors to the thread's Tf.Error list without raising a
    Python exception, halting unwinding.  For example, the following will raise
    a Tf.ErrorException containing the "test" Coding Error.  This will be
    caught by the CatchAndRepostErrors object, and the "test" Error will be
    re-posted to the thread's error list.  Then exception propagation will
    cease and ordinary control flow will continue.

        with Tf.CatchAndRepostErrors():
            Tf.RaiseCodingError('test')

    This can be useful to sidestep SIP's virtual function bindings from
    blocking exceptions, retaining Tf.Errors so they can propagate to callers.
    Here, the `paintGL()` virtual override can capture any Tf.ErrorExceptions
    raised during its execution, and by reposting the errors to the Tf.Error
    list, callers can observe them later.

        @Tf.CatchAndRepostErrors():
        def paintGL(self):
            self._renderer.Render()
    """
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, excType, excValue, tb): # -> Literal[False]:
        ...
    


