"""Minimal local stubs for pxr.Usd while learning USD."""

from typing import Any
from pxr import Sdf


class Prim:
    def GetPath(self) -> Any: ...
    def GetTypeName(self) -> str: ...
    def IsValid(self) -> bool: ...


class Stage:
    @staticmethod
    def CreateInMemory(identifier: str = "") -> "Stage": ...

    @staticmethod
    def CreateNew(identifier: str) -> "Stage": ...

    @staticmethod
    def Open(filePath: str) -> "Stage": ...

    def DefinePrim(self, path: str, typeName: str = "") -> Prim: ...
    def Export(self, filePath: str, addSourceFileComment: bool = True) -> bool: ...
    def ExportToString(self, addSourceFileComment: bool = True) -> str: ...
    def GetDefaultPrim(self) -> Prim: ...
    def GetRootLayer(self) -> Sdf.Layer: ...
    def Save(self) -> bool: ...
    def SetDefaultPrim(self, prim: Prim) -> None: ...