"""Minimal local stubs for pxr.Usd while learning USD."""

from typing import Any
from pxr import Sdf


class Attribute:
    def Get(self) -> Any: ...
    def Set(self, value: Any) -> bool: ...


class Prim:
    def GetAttributes(self) -> list[Attribute]: ...
    def GetChild(self, name: str) -> "Prim": ...
    def GetPath(self) -> Sdf.Path: ...
    def GetPropertyNames(self) -> list[str]: ...
    def GetTypeName(self) -> str: ...
    def IsValid(self) -> bool: ...


class Stage:
    @staticmethod
    def CreateInMemory(identifier: str = "") -> "Stage": ...

    @staticmethod
    def CreateNew(identifier: str) -> "Stage": ...

    @staticmethod
    def Open(filePath: str) -> "Stage": ...

    def DefinePrim(self, path: str, typeName: str = "") -> Prim: ...
    def Export(self, filePath: str, addSourceFileComment: bool = True) -> bool: ...
    def ExportToString(self, addSourceFileComment: bool = True) -> str: ...
    def GetDefaultPrim(self) -> Prim: ...
    def GetPrimAtPath(self, path: Sdf.Path | str) -> Prim: ...
    def GetRootLayer(self) -> Sdf.Layer: ...
    def Save(self) -> bool: ...
    def SetDefaultPrim(self, prim: Prim) -> None: ...
